In [85]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [86]:
credits = pd.read_csv('C://Users//Dell pc//OneDrive//Desktop//tmdb_5000_.csv')
movies = pd.read_csv('C://Users//Dell pc//OneDrive//Desktop//tmdb_5000_movie.csv')

In [87]:
# movies = pd.read_csv('/kaggle/input/tmdb-movie-metadata/tmdb_5000_movies.csv')
# credits = pd.read_csv('/kaggle/input/tmdb-movie-metadata/tmdb_5000_credits.csv')

In [88]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [89]:
movies.shape

(4803, 20)

In [90]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [91]:
movies = movies.merge(credits,on='title')

In [92]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [93]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [94]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [95]:
movies["genres"]

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4809, dtype: object

In [96]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [97]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [98]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [99]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [100]:
movies.dropna(inplace=True)

In [101]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [102]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [103]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [104]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [105]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [106]:
movies['cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [107]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [108]:
movies['cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [109]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [110]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [111]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
4445,157354,Fruitvale Station,"The true story of Oscar, a 22-year-old Bay Are...",[Drama],"[police brutality, based on true story, racism...","[Michael B. Jordan, Octavia Spencer, Melonie D...",[Ryan Coogler]
1821,50014,The Help,Aibileen Clark is a middle-aged African-Americ...,[Drama],"[mississippi, based on novel, exploitation, ra...","[Emma Stone, Viola Davis, Octavia Spencer]",[Tate Taylor]
1494,8055,The Reader,"The story of Michael Berg, a German lawyer who...","[Drama, Romance]","[germany, war crimes, trial, female prisoner, ...","[Kate Winslet, Ralph Fiennes, David Kross]",[Stephen Daldry]
2757,238603,Earth to Echo,After a construction project begins digging in...,"[Family, Adventure, Science Fiction]","[alien, found footage]","[Teo Halm, Astro, Resse Hartwig]",[Dave Green]
1699,87,Indiana Jones and the Temple of Doom,"After arriving in India, Indiana Jones is aske...","[Adventure, Action]","[riddle, treasure, heart, skeleton, treasure h...","[Harrison Ford, Kate Capshaw, Jonathan Ke Quan]",[Steven Spielberg]

In [112]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [113]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [114]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [115]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [116]:
movies['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [117]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [118]:
movies['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4806, dtype: object

In [119]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [120]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [121]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [122]:
vector = cv.fit_transform(new['tags']).toarray()

In [123]:
vector.shape

(4806, 5000)

In [124]:
from sklearn.metrics.pairwise import cosine_similarity

In [125]:
similarity = cosine_similarity(vector)

In [126]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [135]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [134]:
new[new['title'] == 'John Carter']

   movie_id        title                                               tags
4     49529  John Carter  John Carter is a war-weary, former military ca...

In [151]:
index=new[new['title'] == 'The Lego Movie'].index[0]
index

744

In [152]:
distances = sorted(list(enumerate(similarity[index])),reverse=True)
distances

[(4805, 0.0),
 (4804, 0.0),
 (4803, 0.0298142396999972),
 (4802, 0.0632455532033676),
 (4801, 0.02948839123097943),
 (4800, 0.023904572186687872),
 (4799, 0.0),
 (4798, 0.0),
 (4797, 0.048507125007266595),
 (4796, 0.0),
 (4795, 0.031234752377721216),
 (4794, 0.0),
 (4793, 0.0),
 (4792, 0.0),
 (4791, 0.07427813527082075),
 (4790, 0.0),
 (4789, 0.02721655269759087),
 (4788, 0.0),
 (4787, 0.026726124191242442),
 (4786, 0.025607375986579195),
 (4785, 0.06246950475544243),
 (4784, 0.053452248382484885),
 (4783, 0.0),
 (4782, 0.03202563076101743),
 (4781, 0.0),
 (4780, 0.0),
 (4779, 0.04264014327112209),
 (4778, 0.07698003589195011),
 (4777, 0.0),
 (4776, 0.04588314677411235),
 (4775, 0.11547005383792516),
 (4774, 0.0),
 (4773, 0.035355339059327376),
 (4772, 0.0),
 (4771, 0.0),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.0),
 (4766, 0.021566554640687685),
 (4765, 0.0),
 (4764, 0.05773502691896259),
 (4763, 0.05547001962252292),
 (4762, 0.0),
 (4761, 0.0),
 (4760, 0.035355339059327376),
 (4759, 0.02857142857142857),
 (4758, 0.0),
 (4757, 0.11547005383792518),
 (4756, 0.04588314677411235),
 (4755, 0.03244428422615251),
 (4754, 0.0),
 (4753, 0.0632455532033676),
 (4752, 0.07302967433402215),
 (4751, 0.0),
 (4750, 0.05547001962252292),
 (4749, 0.0),
 (4748, 0.0),
 (4747, 0.1),
 (4746, 0.044721359549995794),
 (4745, 0.043643578047198484),
 (4744, 0.03922322702763681),
 (4743, 0.021320071635561044),
 (4742, 0.053452248382484885),
 (4741, 0.0),
 (4740, 0.0),
 (4739, 0.03244428422615251),
 (4738, 0.0),
 (4737, 0.053452248382484885),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.0),
 (4733, 0.04264014327112209),
 (4732, 0.03287979746107146),
 (4731, 0.03592106040535498),
 (4730, 0.0),
 (4729, 0.11094003924504584),
 (4728, 0.031234752377721216),
 (4727, 0.03922322702763681),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0316227766016838),
 (4723, 0.0),
 (4722, 0.0),
 (4721, 0.035355339059327376),
 (4720, 0.07184212081070997),
 (4719, 0.025607375986579195),
 (4718, 0.0),
 (4717, 0.0),
 (4716, 0.0),
 (4715, 0.05547001962252292),
 (4714, 0.0),
 (4713, 0.0),
 (4712, 0.08017837257372733),
 (4711, 0.0),
 (4710, 0.06030226891555273),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.0),
 (4706, 0.015294382258037451),
 (4705, 0.04588314677411235),
 (4704, 0.0),
 (4703, 0.0),
 (4702, 0.0),
 (4701, 0.0),
 (4700, 0.043643578047198484),
 (4699, 0.0),
 (4698, 0.07427813527082075),
 (4697, 0.0),
 (4696, 0.0),
 (4695, 0.08164965809277261),
 (4694, 0.02857142857142857),
 (4693, 0.10776318121606496),
 (4692, 0.0),
 (4691, 0.0),
 (4690, 0.030499714066520935),
 (4689, 0.02948839123097943),
 (4688, 0.0),
 (4687, 0.04264014327112209),
 (4686, 0.037139067635410375),
 (4685, 0.0),
 (4684, 0.043643578047198484),
 (4683, 0.0),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.03849001794597506),
 (4679, 0.0),
 (4678, 0.09116846116771037),
 (4677, 0.0),
 (4676, 0.037139067635410375),
 (4675, 0.0),
 (4674, 0.034299717028501764),
 (4673, 0.07427813527082075),
 (4672, 0.0298142396999972),
 (4671, 0.037139067635410375),
 (4670, 0.0),
 (4669, 0.0),
 (4668, 0.0),
 (4667, 0.0),
 (4666, 0.04082482904638631),
 (4665, 0.05),
 (4664, 0.0),
 (4663, 0.0),
 (4662, 0.0596284793999944),
 (4661, 0.0),
 (4660, 0.0),
 (4659, 0.0),
 (4658, 0.03244428422615251),
 (4657, 0.035355339059327376),
 (4656, 0.05393598899705937),
 (4655, 0.0),
 (4654, 0.0),
 (4653, 0.0),
 (4652, 0.04082482904638631),
 (4651, 0.0),
 (4650, 0.0),
 (4649, 0.07302967433402215),
 (4648, 0.05039526306789696),
 (4647, 0.0),
 (4646, 0.0),
 (4645, 0.0),
 (4644, 0.07559289460184544),
 (4643, 0.053452248382484885),
 (4642, 0.0),
 (4641, 0.0),
 (4640, 0.0632455532033676),
 (4639, 0.026967994498529685),
 (4638, 0.04264014327112209),
 (4637, 0.0),
 (4636, 0.0),
 (4635, 0.10327955589886445),
 (4634, 0.03287979746107146),
 (4633, 0.0),
 (4632, 0.044721359549995794),
 (4631, 0.0),
 (4630, 0.022360679774997897),
 (4629, 0.037139067635410375),
 (4628, 0.0),
 (4627, 0.0),
 (4626, 0.03651483716701107),
 (4625, 0.0),
 (4624, 0.0),
 (4623, 0.04264014327112209),
 (4622, 0.0),
 (4621, 0.0),
 (4620, 0.0),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.05773502691896259),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.09922778767136678),
 (4612, 0.02721655269759087),
 (4611, 0.08728715609439697),
 (4610, 0.028867513459481294),
 (4609, 0.0),
 (4608, 0.0316227766016838),
 (4607, 0.025819888974716113),
 (4606, 0.11094003924504584),
 (4605, 0.0),
 (4604, 0.04588314677411235),
 (4603, 0.0),
 (4602, 0.06666666666666667),
 (4601, 0.0),
 (4600, 0.0),
 (4599, 0.0),
 (4598, 0.03849001794597506),
 (4597, 0.0),
 (4596, 0.0632455532033676),
 (4595, 0.0),
 (4594, 0.0),
 (4593, 0.0),
 (4592, 0.0),
 (4591, 0.04082482904638631),
 (4590, 0.0894427190999916),
 (4589, 0.03481553119113957),
 (4588, 0.0),
 (4587, 0.05547001962252292),
 (4586, 0.0),
 (4585, 0.0),
 (4584, 0.034299717028501764),
 (4583, 0.051639777949432225),
 (4582, 0.06974858324629157),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.03922322702763681),
 (4578, 0.08000000000000002),
 (4577, 0.0),
 (4576, 0.0316227766016838),
 (4575, 0.03779644730092272),
 (4574, 0.022941573387056175),
 (4573, 0.05),
 (4572, 0.0),
 (4571, 0.05547001962252292),
 (4570, 0.0),
 (4569, 0.0),
 (4568, 0.048507125007266595),
 (4567, 0.0),
 (4566, 0.03849001794597506),
 (4565, 0.01881441736767195),
 (4564, 0.053452248382484885),
 (4563, 0.05773502691896259),
 (4562, 0.051639777949432225),
 (4561, 0.0),
 (4560, 0.0),
 (4559, 0.0),
 (4558, 0.0),
 (4557, 0.0),
 (4556, 0.03202563076101743),
 (4555, 0.053452248382484885),
 (4554, 0.0),
 (4553, 0.0),
 (4552, 0.0),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.037139067635410375),
 (4548, 0.05),
 (4547, 0.08320502943378438),
 (4546, 0.06488856845230502),
 (4545, 0.0),
 (4544, 0.0),
 (4543, 0.03481553119113957),
 (4542, 0.16035674514745465),
 (4541, 0.030151134457776365),
 (4540, 0.03481553119113957),
 (4539, 0.0),
 (4538, 0.0),
 (4537, 0.0),
 (4536, 0.0),
 (4535, 0.08944271909999159),
 (4534, 0.0),
 (4533, 0.06666666666666667),
 (4532, 0.02250175801852048),
 (4531, 0.0),
 (4530, 0.0),
 (4529, 0.058345996599157825),
 (4528, 0.0),
 (4527, 0.0),
 (4526, 0.04000000000000001),
 (4525, 0.07878385971583353),
 (4524, 0.0),
 (4523, 0.0),
 (4522, 0.0),
 (4521, 0.08728715609439697),
 (4520, 0.02747211278973781),
 (4519, 0.0),
 (4518, 0.044172610429938614),
 (4517, 0.0),
 (4516, 0.11094003924504584),
 (4515, 0.0),
 (4514, 0.03779644730092272),
 (4513, 0.026967994498529685),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.03481553119113957),
 (4509, 0.08000000000000002),
 (4508, 0.030860669992418384),
 (4507, 0.0),
 (4506, 0.0),
 (4505, 0.0),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.05547001962252292),
 (4501, 0.02649064714130088),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.03202563076101743),
 (4497, 0.04588314677411235),
 (4496, 0.0),
 (4495, 0.0),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.051639777949432225),
 (4491, 0.0),
 (4490, 0.04082482904638631),
 (4489, 0.03980148760839957),
 (4488, 0.0),
 (4487, 0.0),
 (4486, 0.0),
 (4485, 0.0),
 (4484, 0.0),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.0),
 (4476, 0.0),
 (4475, 0.0),
 (4474, 0.051639777949432225),
 (4473, 0.048507125007266595),
 (4472, 0.08528028654224418),
 (4471, 0.0),
 (4470, 0.04170288281141496),
 (4469, 0.0),
 (4468, 0.037139067635410375),
 (4467, 0.04000000000000001),
 (4466, 0.12598815766974242),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.0),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.0),
 (4459, 0.03849001794597506),
 (4458, 0.0),
 (4457, 0.05547001962252292),
 (4456, 0.07302967433402215),
 (4455, 0.0),
 (4454, 0.0),
 (4453, 0.0316227766016838),
 (4452, 0.0),
 (4451, 0.06488856845230502),
 (4450, 0.03202563076101743),
 (4449, 0.024618298195866545),
 (4448, 0.0),
 (4447, 0.0),
 (4446, 0.06246950475544243),
 (4445, 0.07698003589195011),
 (4444, 0.08944271909999159),
 (4443, 0.1341640786499874),
 (4442, 0.044721359549995794),
 (4441, 0.05),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0316227766016838),
 (4437, 0.0),
 (4436, 0.11338934190276817),
 (4435, 0.0),
 (4434, 0.03922322702763681),
 (4433, 0.0),
 (4432, 0.0),
 (4431, 0.0),
 (4430, 0.024806946917841695),
 (4429, 0.024806946917841695),
 (4428, 0.0),
 (4427, 0.0),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.02948839123097943),
 (4422, 0.03333333333333333),
 (4421, 0.04170288281141496),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.0),
 (4414, 0.0),
 (4413, 0.03651483716701107),
 (4412, 0.0),
 (4411, 0.05),
 (4410, 0.0),
 (4409, 0.13333333333333333),
 (4408, 0.04082482904638631),
 (4407, 0.10327955589886445),
 (4406, 0.0),
 (4405, 0.11547005383792518),
 (4404, 0.0),
 (4403, 0.044721359549995794),
 (4402, 0.0),
 (4401, 0.0),
 (4400, 0.14142135623730953),
 (4399, 0.029172998299578912),
 (4398, 0.02948839123097943),
 (4397, 0.0),
 (4396, 0.03651483716701107),
 (4395, 0.11547005383792518),
 (4394, 0.0),
 (4393, 0.0),
 (4392, 0.0),
 (4391, 0.10690449676496977),
 (4390, 0.048507125007266595),
 (4389, 0.0),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.05601120336112039),
 (4383, 0.0),
 (4382, 0.09258200997725516),
 (4381, 0.035355339059327376),
 (4380, 0.0),
 (4379, 0.0),
 (4378, 0.05547001962252292),
 (4377, 0.0),
 (4376, 0.029172998299578912),
 (4375, 0.0),
 (4374, 0.0),
 (4373, 0.0),
 (4372, 0.06405126152203486),
 (4371, 0.030151134457776365),
 (4370, 0.0),
 (4369, 0.0316227766016838),
 (4368, 0.0),
 (4367, 0.0),
 (4366, 0.0),
 (4365, 0.051639777949432225),
 (4364, 0.0),
 (4363, 0.0),
 (4362, 0.053452248382484885),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.02857142857142857),
 (4358, 0.028005601680560196),
 (4357, 0.04170288281141496),
 (4356, 0.0),
 (4355, 0.0),
 (4354, 0.0),
 (4353, 0.0),
 (4352, 0.0632455532033676),
 (4351, 0.0),
 (4350, 0.0316227766016838),
 (4349, 0.0),
 (4348, 0.05547001962252292),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.0),
 (4343, 0.029172998299578912),
 (4342, 0.0),
 (4341, 0.0),
 (4340, 0.0),
 (4339, 0.07184212081070997),
 (4338, 0.04588314677411235),
 (4337, 0.0),
 (4336, 0.03202563076101743),
 (4335, 0.03244428422615251),
 (4334, 0.058345996599157825),
 (4333, 0.0),
 (4332, 0.0),
 (4331, 0.0),
 (4330, 0.0),
 (4329, 0.033806170189140665),
 (4328, 0.04082482904638631),
 (4327, 0.0),
 (4326, 0.0),
 (4325, 0.0298142396999972),
 (4324, 0.0),
 (4323, 0.033806170189140665),
 (4322, 0.0),
 (4321, 0.051639777949432225),
 (4320, 0.04170288281141496),
 (4319, 0.04147806778921701),
 (4318, 0.0),
 (4317, 0.0),
 (4316, 0.03481553119113957),
 (4315, 0.1414213562373095),
 (4314, 0.14142135623730953),
 (4313, 0.07559289460184544),
 (4312, 0.0),
 (4311, 0.043643578047198484),
 (4310, 0.0),
 (4309, 0.06666666666666667),
 (4308, 0.06030226891555273),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.07330166661378314),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.033806170189140665),
 (4301, 0.03922322702763681),
 (4300, 0.0),
 (4299, 0.03202563076101743),
 (4298, 0.05),
 (4297, 0.0),
 (4296, 0.07559289460184544),
 (4295, 0.0),
 (4294, 0.0),
 (4293, 0.06666666666666667),
 (4292, 0.0),
 (4291, 0.0),
 (4290, 0.21821789023599242),
 (4289, 0.033806170189140665),
 (4288, 0.03244428422615251),
 (4287, 0.0),
 (4286, 0.0),
 (4285, 0.0),
 (4284, 0.0),
 (4283, 0.08944271909999159),
 (4282, 0.04082482904638631),
 (4281, 0.1264911064067352),
 (4280, 0.0282842712474619),
 (4279, 0.05773502691896259),
 (4278, 0.0632455532033676),
 (4277, 0.023408229439226116),
 (4276, 0.051639777949432225),
 (4275, 0.02948839123097943),
 (4274, 0.06172133998483677),
 (4273, 0.04170288281141496),
 (4272, 0.037139067635410375),
 (4271, 0.15689290811054724),
 (4270, 0.1460593486680443),
 (4269, 0.0),
 (4268, 0.0),
 (4267, 0.0),
 (4266, 0.031234752377721216),
 (4265, 0.05443310539518174),
 (4264, 0.0),
 (4263, 0.0),
 (4262, 0.09370425713316365),
 (4261, 0.03202563076101743),
 (4260, 0.0),
 (4259, 0.0),
 (4258, 0.13151918984428584),
 (4257, 0.0),
 (4256, 0.047140452079103175),
 (4255, 0.04588314677411235),
 (4254, 0.08164965809277262),
 (4253, 0.030860669992418384),
 (4252, 0.04264014327112209),
 (4251, 0.0),
 (4250, 0.02169304578186562),
 (4249, 0.0),
 (4248, 0.035355339059327376),
 (4247, 0.053452248382484885),
 (4246, 0.0),
 (4245, 0.0565685424949238),
 (4244, 0.0632455532033676),
 (4243, 0.0917662935482247),
 (4242, 0.03577708763999664),
 (4241, 0.05),
 (4240, 0.048507125007266595),
 (4239, 0.0),
 (4238, 0.03333333333333333),
 (4237, 0.0),
 (4236, 0.0),
 (4235, 0.0),
 (4234, 0.0),
 (4233, 0.022645540682891915),
 (4232, 0.037139067635410375),
 (4231, 0.0316227766016838),
 (4230, 0.0),
 (4229, 0.0),
 (4228, 0.03202563076101743),
 (4227, 0.08528028654224418),
 (4226, 0.04264014327112209),
 (4225, 0.0),
 (4224, 0.028005601680560196),
 (4223, 0.020203050891044214),
 (4222, 0.035355339059327376),
 (4221, 0.04170288281141496),
 (4220, 0.023904572186687872),
 (4219, 0.021821789023599242),
 (4218, 0.0),
 (4217, 0.047140452079103175),
 (4216, 0.0),
 (4215, 0.0),
 (4214, 0.0),
 (4213, 0.0),
 (4212, 0.0),
 (4211, 0.0),
 (4210, 0.053452248382484885),
 (4209, 0.03592106040535498),
 (4208, 0.0),
 (4207, 0.06761234037828133),
 (4206, 0.035355339059327376),
 (4205, 0.0),
 (4204, 0.0),
 (4203, 0.06666666666666667),
 (4202, 0.04264014327112209),
 (4201, 0.1),
 (4200, 0.0),
 (4199, 0.037139067635410375),
 (4198, 0.0),
 (4197, 0.028867513459481294),
 (4196, 0.0),
 (4195, 0.0),
 (4194, 0.11766968108291043),
 (4193, 0.0),
 (4192, 0.0),
 (4191, 0.04082482904638631),
 (4190, 0.0),
 (4189, 0.043643578047198484),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.0),
 (4185, 0.03333333333333333),
 (4184, 0.05547001962252292),
 (4183, 0.1341640786499874),
 (4182, 0.04082482904638631),
 (4181, 0.0),
 (4180, 0.0),
 (4179, 0.0),
 (4178, 0.08846517369293828),
 (4177, 0.0),
 (4176, 0.05601120336112039),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.09370425713316365),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.0),
 (4169, 0.051639777949432225),
 (4168, 0.0),
 (4167, 0.0),
 (4166, 0.07071067811865475),
 (4165, 0.0),
 (4164, 0.03849001794597506),
 (4163, 0.051639777949432225),
 (4162, 0.0),
 (4161, 0.02857142857142857),
 (4160, 0.0),
 (4159, 0.022222222222222223),
 (4158, 0.02857142857142857),
 (4157, 0.0),
 (4156, 0.043643578047198484),
 (4155, 0.08944271909999159),
 (4154, 0.0),
 (4153, 0.06666666666666667),
 (4152, 0.05393598899705937),
 (4151, 0.06030226891555273),
 (4150, 0.04588314677411235),
 (4149, 0.03368607684266076),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.07559289460184544),
 (4145, 0.0),
 (4144, 0.04588314677411235),
 (4143, 0.0),
 (4142, 0.0),
 (4141, 0.0),
 (4140, 0.0),
 (4139, 0.0),
 (4138, 0.047140452079103175),
 (4137, 0.0),
 (4136, 0.0),
 (4135, 0.0),
 (4134, 0.06963106238227915),
 (4133, 0.044721359549995794),
 (4132, 0.03849001794597506),
 (4131, 0.02721655269759087),
 (4130, 0.044721359549995794),
 (4129, 0.1),
 (4128, 0.0),
 (4127, 0.10259783520851543),
 (4126, 0.0),
 (4125, 0.030499714066520935),
 (4124, 0.05773502691896259),
 (4123, 0.06761234037828133),
 (4122, 0.0),
 (4121, 0.030860669992418384),
 (4120, 0.043643578047198484),
 (4119, 0.11766968108291043),
 (4118, 0.0),
 (4117, 0.07427813527082075),
 (4116, 0.05547001962252292),
 (4115, 0.0),
 (4114, 0.0),
 (4113, 0.0),
 (4112, 0.0),
 (4111, 0.0),
 (4110, 0.0),
 (4109, 0.04558423058385518),
 (4108, 0.07427813527082075),
 (4107, 0.034299717028501764),
 (4106, 0.04588314677411235),
 (4105, 0.08000000000000002),
 (4104, 0.0),
 (4103, 0.0),
 (4102, 0.0),
 (4101, 0.0298142396999972),
 (4100, 0.0),
 (4099, 0.031234752377721216),
 (4098, 0.026967994498529685),
 (4097, 0.044721359549995794),
 (4096, 0.06575959492214292),
 (4095, 0.0),
 (4094, 0.02721655269759087),
 (4093, 0.0),
 (4092, 0.0),
 (4091, 0.047140452079103175),
 (4090, 0.052075564392329556),
 (4089, 0.11338934190276817),
 (4088, 0.04082482904638631),
 (4087, 0.0),
 (4086, 0.0),
 (4085, 0.0),
 (4084, 0.03481553119113957),
 (4083, 0.0),
 (4082, 0.09863939238321438),
 (4081, 0.030860669992418384),
 (4080, 0.022941573387056175),
 (4079, 0.05773502691896259),
 (4078, 0.0),
 (4077, 0.03244428422615251),
 (4076, 0.10289915108550529),
 (4075, 0.051639777949432225),
 (4074, 0.048507125007266595),
 (4073, 0.0),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.0),
 (4068, 0.035355339059327376),
 (4067, 0.03287979746107146),
 (4066, 0.02948839123097943),
 (4065, 0.06030226891555273),
 (4064, 0.043643578047198484),
 (4063, 0.11141720290623112),
 (4062, 0.0),
 (4061, 0.09045340337332909),
 (4060, 0.0),
 (4059, 0.05),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.0),
 (4055, 0.044721359549995794),
 (4054, 0.1),
 (4053, 0.22710998958306758),
 (4052, 0.0),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.052075564392329556),
 (4048, 0.04020151261036849),
 (4047, 0.048507125007266595),
 (4046, 0.052075564392329556),
 (4045, 0.03287979746107146),
 (4044, 0.0),
 (4043, 0.06246950475544243),
 (4042, 0.0),
 (4041, 0.0),
 (4040, 0.0),
 (4039, 0.05547001962252292),
 (4038, 0.1455213750217998),
 (4037, 0.07071067811865475),
 (4036, 0.0),
 (4035, 0.0),
 (4034, 0.05547001962252292),
 (4033, 0.0),
 (4032, 0.021081851067789197),
 (4031, 0.0),
 (4030, 0.0),
 (4029, 0.03244428422615251),
 (4028, 0.044721359549995794),
 (4027, 0.043643578047198484),
 (4026, 0.07022468831767835),
 (4025, 0.043643578047198484),
 (4024, 0.05),
 (4023, 0.043643578047198484),
 (4022, 0.0),
 (4021, 0.0),
 (4020, 0.06488856845230502),
 (4019, 0.05443310539518174),
 (4018, 0.09428090415820635),
 (4017, 0.0),
 (4016, 0.0),
 (4015, 0.0),
 (4014, 0.047140452079103175),
 (4013, 0.0),
 (4012, 0.11094003924504584),
 (4011, 0.0),
 (4010, 0.024806946917841695),
 (4009, 0.0),
 (4008, 0.15000000000000002),
 (4007, 0.0),
 (4006, 0.0),
 (4005, 0.0632455532033676),
 (4004, 0.0),
 (4003, 0.035355339059327376),
 (4002, 0.0),
 (4001, 0.04923659639173309),
 (4000, 0.0),
 (3999, 0.05547001962252292),
 (3998, 0.0917662935482247),
 (3997, 0.12792042981336627),
 (3996, 0.0),
 (3995, 0.058345996599157825),
 (3994, 0.053452248382484885),
 (3993, 0.07844645405527362),
 (3992, 0.0),
 (3991, 0.02407717061715384),
 (3990, 0.12060453783110546),
 (3989, 0.0316227766016838),
 (3988, 0.06099942813304187),
 (3987, 0.0),
 (3986, 0.0),
 (3985, 0.07844645405527362),
 (3984, 0.05547001962252292),
 (3983, 0.0),
 (3982, 0.0),
 (3981, 0.08000000000000002),
 (3980, 0.0),
 (3979, 0.01849000654084097),
 (3978, 0.0),
 (3977, 0.044721359549995794),
 (3976, 0.0),
 (3975, 0.0),
 (3974, 0.0),
 (3973, 0.0),
 (3972, 0.0),
 (3971, 0.12247448713915893),
 (3970, 0.0),
 (3969, 0.0),
 (3968, 0.053452248382484885),
 (3967, 0.0632455532033676),
 (3966, 0.0),
 (3965, 0.0),
 (3964, 0.11547005383792518),
 (3963, 0.03592106040535498),
 (3962, 0.0),
 (3961, 0.0),
 (3960, 0.0),
 (3959, 0.025400025400038103),
 (3958, 0.044444444444444446),
 (3957, 0.03287979746107146),
 (3956, 0.07878385971583353),
 (3955, 0.053452248382484885),
 (3954, 0.03779644730092272),
 (3953, 0.048507125007266595),
 (3952, 0.043643578047198484),
 (3951, 0.03592106040535498),
 (3950, 0.03481553119113957),
 (3949, 0.06060915267313265),
 (3948, 0.0282842712474619),
 (3947, 0.05547001962252292),
 (3946, 0.022222222222222223),
 (3945, 0.05443310539518174),
 (3944, 0.0),
 (3943, 0.037139067635410375),
 (3942, 0.06666666666666667),
 (3941, 0.08528028654224418),
 (3940, 0.0),
 (3939, 0.10327955589886445),
 (3938, 0.0298142396999972),
 (3937, 0.03779644730092272),
 (3936, 0.0),
 (3935, 0.0),
 (3934, 0.0316227766016838),
 (3933, 0.10776318121606496),
 (3932, 0.06575959492214292),
 (3931, 0.03922322702763681),
 (3930, 0.030499714066520935),
 (3929, 0.04170288281141496),
 (3928, 0.09370425713316365),
 (3927, 0.0),
 (3926, 0.025819888974716113),
 (3925, 0.0),
 (3924, 0.03651483716701107),
 (3923, 0.13333333333333333),
 (3922, 0.0),
 (3921, 0.05773502691896259),
 (3920, 0.0),
 (3919, 0.07330166661378314),
 (3918, 0.0),
 (3917, 0.0),
 (3916, 0.1455213750217998),
 (3915, 0.0),
 (3914, 0.0),
 (3913, 0.03202563076101743),
 (3912, 0.0),
 (3911, 0.05039526306789696),
 (3910, 0.03244428422615251),
 (3909, 0.03922322702763681),
 (3908, 0.09863939238321438),
 (3907, 0.0),
 (3906, 0.024618298195866545),
 (3905, 0.1874085142663273),
 (3904, 0.04728662437434604),

In [153]:
distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
distances

[(744, 1.0000000000000004),
 (503, 0.29591817714964314),
 (742, 0.28577380332470415),
 (934, 0.28284271247461895),
 (368, 0.28),
 (179, 0.2683281572999748),
 (2529, 0.2683281572999748),
 (234, 0.2672612419124244),
 (254, 0.2630383796885717),
 (506, 0.2618614682831909),
 (546, 0.25584085962673253),
 (942, 0.2514474228374849),
 (1278, 0.25021729686848976),
 (558, 0.25),
 (359, 0.24494897427831788),
 (1985, 0.24120907566221092),
 (3405, 0.2385139175999776),
 (1697, 0.23590712984783543),
 (154, 0.23533936216582085),
 (1135, 0.23533936216582085),
 (40, 0.23333333333333334),
 (131, 0.23333333333333334),
 (4053, 0.22710998958306758),
 (73, 0.223606797749979),
 (1063, 0.22283440581246222),
 (325, 0.21821789023599242),
 (4290, 0.21821789023599242),
 (1102, 0.21380899352993954),
 (459, 0.21320071635561044),
 (294, 0.21213203435596426),
 (410, 0.2086996778999804),
 (2558, 0.2085144140570748),
 (810, 0.20579830217101058),
 (2682, 0.20579830217101058),
 (221, 0.2042109880970524),
 (2592, 0.2042109880970524),
 (1377, 0.20412414523193156),
 (2327, 0.20412414523193156),
 (42, 0.20207259421636906),
 (348, 0.20000000000000004),
 (604, 0.20000000000000004),
 (187, 0.2),
 (569, 0.2),
 (144, 0.19727878476642874),
 (2116, 0.19611613513818404),
 (3283, 0.19466570535691508),
 (142, 0.1924500897298753),
 (195, 0.1924500897298753),
 (90, 0.19245008972987526),
 (1688, 0.19230478952816465),
 (1288, 0.1921537845661046),
 (130, 0.1889822365046136),
 (3858, 0.1889822365046136),
 (124, 0.1887759614897078),
 (343, 0.1887759614897078),
 (109, 0.1885618083164127),
 (435, 0.1885618083164127),
 (2655, 0.1885618083164127),
 (3905, 0.1874085142663273),
 (306, 0.18569533817705186),
 (1247, 0.18569533817705186),
 (778, 0.1851640199545103),
 (374, 0.18382900600361157),
 (1723, 0.1835325870964494),
 (1888, 0.1835325870964494),
 (429, 0.18257418583505536),
 (978, 0.18257418583505536),
 (1684, 0.18257418583505536),
 (3047, 0.18090680674665818),
 (117, 0.17960530202677494),
 (121, 0.17960530202677494),
 (2141, 0.17960530202677494),
 (141, 0.17888543819998318),
 (418, 0.17888543819998318),
 (66, 0.17693034738587657),
 (566, 0.17693034738587657),
 (514, 0.17677669529663687),
 (572, 0.17638342073763938),
 (1192, 0.17457431218879393),
 (86, 0.17407765595569785),
 (196, 0.17407765595569785),
 (899, 0.17407765595569785),
 (1030, 0.17407765595569785),
 (3006, 0.17407765595569785),
 (1551, 0.17364862842489187),
 (2466, 0.17320508075688776),
 (3273, 0.17320508075688776),
 (837, 0.17149858514250882),
 (3127, 0.17056057308448835),
 (3131, 0.17056057308448835),
 (3582, 0.17056057308448835),
 (3627, 0.17056057308448835),
 (1041, 0.16970562748477142),
 (460, 0.16903085094570333),
 (1258, 0.1690308509457033),
 (1384, 0.1690308509457033),
 (194, 0.16681153124565984),
 (533, 0.16681153124565984),
 (935, 0.16681153124565984),
 (1658, 0.16681153124565984),
 (390, 0.16666666666666669),
 (258, 0.16641005886756877),
 (2129, 0.16641005886756877),
 (2852, 0.16641005886756877),
 (3183, 0.16641005886756877),
 (848, 0.16499158227686112),
 (1087, 0.16499158227686112),
 (1079, 0.1643989873053573),
 (2679, 0.1643989873053573),
 (3468, 0.1643989873053573),
 (428, 0.16385760607458283),
 (202, 0.16329931618554525),
 (781, 0.16329931618554525),
 (2097, 0.16329931618554525),
 (1589, 0.16329931618554522),
 (268, 0.16222142113076254),
 (631, 0.16222142113076254),
 (874, 0.16222142113076254),
 (1428, 0.16222142113076254),
 (1736, 0.16222142113076254),
 (1858, 0.16035674514745465),
 (4542, 0.16035674514745465),
 (754, 0.16012815380508716),
 (292, 0.16000000000000003),
 (1075, 0.16000000000000003),
 (1199, 0.16000000000000003),
 (1622, 0.16000000000000003),
 (106, 0.15894388284780528),
 (689, 0.158113883008419),
 (269, 0.15689290811054724),
 (309, 0.15689290811054724),
 (358, 0.15689290811054724),
 (791, 0.15689290811054724),
 (1045, 0.15689290811054724),
 (1215, 0.15689290811054724),
 (1564, 0.15689290811054724),
 (1582, 0.15689290811054724),
 (1654, 0.15689290811054724),
 (4271, 0.15689290811054724),
 (2274, 0.15491933384829668),
 (184, 0.1543033499620919),
 (543, 0.1543033499620919),
 (2746, 0.1543033499620919),
 (3538, 0.1543033499620919),
 (1972, 0.15396007178390023),
 (175, 0.15249857033260467),
 (178, 0.15249857033260467),
 (420, 0.15249857033260467),
 (431, 0.15249857033260467),
 (743, 0.15249857033260467),
 (2901, 0.15249857033260467),
 (1359, 0.1524001524002286),
 (152, 0.15118578920369088),
 (452, 0.15118578920369088),
 (931, 0.15118578920369088),
 (15, 0.15075567228888181),
 (933, 0.15075567228888181),
 (858, 0.15000000000000002),
 (1900, 0.15000000000000002),
 (2039, 0.15000000000000002),
 (4008, 0.15000000000000002),
 (289, 0.149071198499986),
 (734, 0.14907119849998599),
 (492, 0.1485562705416415),
 (960, 0.1485562705416415),
 (1068, 0.1485562705416415),
 (2071, 0.1485562705416415),
 (2542, 0.1485562705416415),
 (2813, 0.1485562705416415),
 (84, 0.14770978917519928),
 (243, 0.14744195615489714),
 (525, 0.14744195615489714),
 (1827, 0.14744195615489714),
 (111, 0.1460593486680443),
 (328, 0.1460593486680443),
 (349, 0.1460593486680443),
 (385, 0.1460593486680443),
 (4270, 0.1460593486680443),
 (896, 0.14586499149789456),
 (465, 0.1455213750217998),
 (1207, 0.1455213750217998),
 (1660, 0.1455213750217998),
 (3153, 0.1455213750217998),
 (3916, 0.1455213750217998),
 (4038, 0.1455213750217998),
 (41, 0.14433756729740646),
 (88, 0.14368424162141993),
 (235, 0.14368424162141993),
 (302, 0.14368424162141993),
 (441, 0.14368424162141993),
 (937, 0.14368424162141993),
 (1332, 0.14368424162141993),
 (2326, 0.14368424162141993),
 (2572, 0.14368424162141993),
 (2812, 0.14368424162141993),
 (578, 0.14285714285714285),
 (177, 0.14142135623730953),
 (313, 0.14142135623730953),
 (1498, 0.14142135623730953),
 (1952, 0.14142135623730953),
 (4314, 0.14142135623730953),
 (4400, 0.14142135623730953),
 (67, 0.1414213562373095),
 (241, 0.1414213562373095),
 (859, 0.1414213562373095),
 (1543, 0.1414213562373095),
 (2358, 0.1414213562373095),
 (2540, 0.1414213562373095),
 (3089, 0.1414213562373095),
 (4315, 0.1414213562373095),
 (92, 0.140028008402801),
 (458, 0.140028008402801),
 (1581, 0.1392621247645583),
 (3426, 0.1392621247645583),
 (181, 0.1386750490563073),
 (1763, 0.1386750490563073),
 (2187, 0.1386750490563073),
 (2834, 0.1386750490563073),
 (20, 0.13764944032233706),
 (160, 0.13764944032233706),
 (2365, 0.13764944032233706),
 (2619, 0.13764944032233706),
 (126, 0.13719886811400706),
 (539, 0.13719886811400706),
 (1735, 0.13719886811400706),
 (1979, 0.13719886811400706),
 (2296, 0.13719886811400706),
 (2763, 0.13719886811400706),
 (3673, 0.13719886811400706),
 (63, 0.13608276348795434),
 (565, 0.13608276348795434),
 (812, 0.13608276348795434),
 (2001, 0.13608276348795434),
 (55, 0.1358732440973515),
 (14, 0.13522468075656266),
 (545, 0.13522468075656266),
 (725, 0.13522468075656266),
 (1902, 0.13522468075656266),
 (2124, 0.13522468075656266),
 (2249, 0.13522468075656266),
 (3496, 0.13522468075656266),
 (3549, 0.13522468075656266),
 (488, 0.13501054811112287),
 (172, 0.1341640786499874),
 (494, 0.1341640786499874),
 (748, 0.1341640786499874),
 (1172, 0.1341640786499874),
 (1766, 0.1341640786499874),
 (3094, 0.1341640786499874),
 (3477, 0.1341640786499874),
 (3714, 0.1341640786499874),
 (4183, 0.1341640786499874),
 (4443, 0.1341640786499874),
 (836, 0.1336306209562122),
 (37, 0.13333333333333333),
 (393, 0.13333333333333333),
 (485, 0.13333333333333333),
 (2614, 0.13333333333333333),
 (3450, 0.13333333333333333),
 (3802, 0.13333333333333333),
 (3923, 0.13333333333333333),
 (4409, 0.13333333333333333),
 (413, 0.13151918984428584),
 (518, 0.13151918984428584),
 (4258, 0.13151918984428584),
 (336, 0.13093073414159545),
 (707, 0.13093073414159545),
 (1164, 0.13093073414159545),
 (1341, 0.13093073414159545),
 (1733, 0.13093073414159545),
 (2459, 0.13093073414159545),
 (2527, 0.13093073414159545),
 (3053, 0.13093073414159545),
 (3779, 0.13093073414159545),
 (403, 0.13018891098082389),
 (138, 0.12977713690461004),
 (481, 0.12977713690461004),
 (563, 0.12977713690461004),
 (2353, 0.12977713690461004),
 (3310, 0.12977713690461004),
 (1596, 0.12909944487358058),
 (949, 0.12909944487358055),
 (1297, 0.12810252304406972),
 (2051, 0.12810252304406972),
 (2272, 0.12810252304406972),
 (2824, 0.12810252304406972),
 (375, 0.12803687993289598),
 (3615, 0.12803687993289598),
 (61, 0.12792042981336627),
 (495, 0.12792042981336627),
 (1848, 0.12792042981336627),
 (3997, 0.12792042981336627),
 (305, 0.1270001270001905),
 (1779, 0.1264911064067352),
 (2105, 0.1264911064067352),
 (3724, 0.1264911064067352),
 (3781, 0.1264911064067352),
 (4281, 0.1264911064067352),
 (4466, 0.12598815766974242),
 (54, 0.12510864843424488),
 (118, 0.12510864843424488),
 (148, 0.12510864843424488),
 (237, 0.12510864843424488),
 (263, 0.12510864843424488),
 (766, 0.12510864843424488),
 (797, 0.12510864843424488),
 (1067, 0.12510864843424488),
 (1521, 0.12510864843424488),
 (1880, 0.12510864843424488),
 (2680, 0.12510864843424488),
 (2739, 0.12510864843424488),
 (2764, 0.12510864843424488),
 (3058, 0.12510864843424488),
 (3141, 0.12510864843424488),
 (3534, 0.12510864843424488),
 (3674, 0.12510864843424488),
 (2976, 0.125),
 (114, 0.12493900951088487),
 (324, 0.12493900951088487),
 (1365, 0.12493900951088487),
 (2340, 0.12493900951088487),
 (2827, 0.12493900951088487),
 (364, 0.12344267996967354),
 (639, 0.12344267996967354),
 (784, 0.12344267996967354),
 (1323, 0.12344267996967354),
 (2222, 0.12344267996967354),
 (299, 0.12309149097933272),
 (34, 0.12247448713915893),
 (903, 0.12247448713915893),
 (1829, 0.12247448713915893),
 (1856, 0.12247448713915893),
 (1969, 0.12247448713915893),
 (2264, 0.12247448713915893),
 (2305, 0.12247448713915893),
 (2657, 0.12247448713915893),
 (3971, 0.12247448713915893),
 (9, 0.12199885626608374),
 (399, 0.12199885626608374),
 (509, 0.12199885626608374),
 (870, 0.12199885626608374),
 (1143, 0.12199885626608374),
 (1496, 0.12199885626608374),
 (2211, 0.12199885626608374),
 (391, 0.12126781251816648),
 (136, 0.12060453783110546),
 (857, 0.12060453783110546),
 (897, 0.12060453783110546),
 (1073, 0.12060453783110546),
 (1274, 0.12060453783110546),
 (1968, 0.12060453783110546),
 (2745, 0.12060453783110546),
 (3886, 0.12060453783110546),
 (3990, 0.12060453783110546),
 (1422, 0.12038585308576921),
 (276, 0.12000000000000002),
 (686, 0.12000000000000002),
 (691, 0.12000000000000002),
 (1156, 0.12000000000000002),
 (1404, 0.12000000000000002),
 (1898, 0.12000000000000002),
 (2967, 0.12),
 (7, 0.1192569587999888),
 (3388, 0.1192569587999888),
 (1934, 0.11795356492391772),
 (2487, 0.11795356492391772),
 (3055, 0.11795356492391772),
 (133, 0.11766968108291043),
 (769, 0.11766968108291043),
 (1056, 0.11766968108291043),
 (1682, 0.11766968108291043),
 (1720, 0.11766968108291043),
 (2511, 0.11766968108291043),
 (2621, 0.11766968108291043),
 (2741, 0.11766968108291043),
 (3609, 0.11766968108291043),
 (4119, 0.11766968108291043),
 (4194, 0.11766968108291043),
 (2178, 0.11704114719613058),
 (618, 0.11669199319831565),
 (704, 0.11669199319831565),
 (318, 0.11547005383792518),
 (979, 0.11547005383792518),
 (1440, 0.11547005383792518),
 (1748, 0.11547005383792518),
 (1864, 0.11547005383792518),
 (3152, 0.11547005383792518),
 (3964, 0.11547005383792518),
 (4395, 0.11547005383792518),
 (4405, 0.11547005383792518),
 (4757, 0.11547005383792518),
 (23, 0.11547005383792516),
 (1430, 0.11547005383792516),
 (2123, 0.11547005383792516),
 (2344, 0.11547005383792516),
 (3255, 0.11547005383792516),
 (4775, 0.11547005383792516),
 (464, 0.11428571428571428),
 (692, 0.11428571428571428),
 (8, 0.11338934190276817),
 (1523, 0.11338934190276817),
 (1678, 0.11338934190276817),
 (2836, 0.11338934190276817),
 (3478, 0.11338934190276817),
 (3579, 0.11338934190276817),
 (4089, 0.11338934190276817),
 (4436, 0.11338934190276817),
 (1307, 0.11322770341445958),
 (1122, 0.1131370849898476),
 (1455, 0.1131370849898476),
 (1920, 0.1131370849898476),
 (2021, 0.1131370849898476),
 (612, 0.11202240672224079),
 (698, 0.11202240672224079),
 (1153, 0.11202240672224079),
 (2754, 0.11202240672224079),
 (3568, 0.11202240672224079),
 (917, 0.11141720290623112),
 (1511, 0.11141720290623112),
 (1580, 0.11141720290623112),
 (1756, 0.11141720290623112),
 (1989, 0.11141720290623112),
 (2070, 0.11141720290623112),
 (2925, 0.11141720290623112),
 (4063, 0.11141720290623112),
 (3061, 0.11094003924504584),
 (3280, 0.11094003924504584),
 (4012, 0.11094003924504584),
 (4516, 0.11094003924504584),
 (4606, 0.11094003924504584),
 (4729, 0.11094003924504584),
 (3329, 0.11043152607484653),
 (6, 0.10988845115895124),
 (143, 0.10988845115895124),
 (673, 0.10988845115895124),
 (1499, 0.10988845115895124),
 (227, 0.10954451150103323),
 (288, 0.10954451150103323),
 (341, 0.10954451150103323),
 (369, 0.10954451150103323),
 (554, 0.10954451150103323),
 (843, 0.10954451150103323),
 (987, 0.10954451150103323),
 (1002, 0.10954451150103323),
 (1148, 0.10954451150103323),
 (1978, 0.10954451150103323),
 (2398, 0.10954451150103323),
 (3364, 0.10954451150103323),
 (3845, 0.10954451150103323),
 (777, 0.10886621079036347),
 (32, 0.10787197799411874),
 (245, 0.10776318121606496),
 (614, 0.10776318121606496),
 (814, 0.10776318121606496),
 (926, 0.10776318121606496),
 (1705, 0.10776318121606496),
 (1881, 0.10776318121606496),
 (1884, 0.10776318121606496),
 (1887, 0.10776318121606496),
 (2118, 0.10776318121606496),
 (2165, 0.10776318121606496),
 (2806, 0.10776318121606496),
 (2822, 0.10776318121606496),
 (3069, 0.10776318121606496),
 (3249, 0.10776318121606496),
 (3933, 0.10776318121606496),
 (4693, 0.10776318121606496),
 (48, 0.10690449676496977),
 (381, 0.10690449676496977),
 (998, 0.10690449676496977),
 (1578, 0.10690449676496977),
 (2435, 0.10690449676496977),
 (2721, 0.10690449676496977),
 (3015, 0.10690449676496977),
 (3128, 0.10690449676496977),
 (3279, 0.10690449676496977),
 (3527, 0.10690449676496977),
 (4391, 0.10690449676496977),
 (232, 0.10606601717798213),
 (1235, 0.10606601717798213),
 (1402, 0.10606601717798213),
 (2168, 0.10606601717798213),
 (2192, 0.10606601717798213),
 (2247, 0.10606601717798213),
 (2300, 0.10606601717798213),
 (2445, 0.10606601717798213),
 (3240, 0.10606601717798213),
 (3247, 0.10606601717798213),
 (551, 0.10596258856520352),
 (2102, 0.10596258856520352),
 (77, 0.10524696231684352),
 (103, 0.10504514628777804),
 (1483, 0.10504514628777804),
 (10, 0.10444659357341872),
 (39, 0.10444659357341872),
 (46, 0.10444659357341872),
 (98, 0.10444659357341872),
 (265, 0.10444659357341872),
 (352, 0.10444659357341872),
 (411, 0.10444659357341872),
 (427, 0.10444659357341872),
 (443, 0.10444659357341872),
 (1593, 0.10444659357341872),
 (1823, 0.10444659357341872),
 (2579, 0.10444659357341872),
 (3003, 0.10444659357341872),
 (3051, 0.10444659357341872),
 (3220, 0.10444659357341872),
 (3892, 0.1044465935734187),
 (501, 0.10415112878465911),
 (1824, 0.10415112878465911),
 (406, 0.10327955589886445),
 (1373, 0.10327955589886445),
 (1405, 0.10327955589886445),
 (1685, 0.10327955589886445),
 (1692, 0.10327955589886445),
 (2114, 0.10327955589886445),
 (2328, 0.10327955589886445),
 (2335, 0.10327955589886445),
 (2530, 0.10327955589886445),
 (2670, 0.10327955589886445),
 (3067, 0.10327955589886445),
 (3939, 0.10327955589886445),
 (4407, 0.10327955589886445),
 (4635, 0.10327955589886445),
 (327, 0.10289915108550529),
 (521, 0.10289915108550529),
 (1691, 0.10289915108550529),
 (2160, 0.10289915108550529),
 (2179, 0.10289915108550529),
 (2265, 0.10289915108550529),
 (3166, 0.10289915108550529),
 (3846, 0.10289915108550529),
 (4076, 0.10289915108550529),
 (4127, 0.10259783520851543),
 (496, 0.10160010160015241),
 (3585, 0.10160010160015241),
 (3135, 0.101418510567422),
 (332, 0.10141851056742199),
 (339, 0.10141851056742199),
 (550, 0.10141851056742199),
 (636, 0.10141851056742199),
 (646, 0.10141851056742199),
 (1218, 0.10141851056742199),
 (1412, 0.10141851056742199),
 (238, 0.10079052613579392),
 (120, 0.1),
 (208, 0.1),
 (255, 0.1),
 (472, 0.1),
 (661, 0.1),
 (906, 0.1),
 (1571, 0.1),
 (1712, 0.1),
 (1941, 0.1),
 (1982, 0.1),
 (2161, 0.1),
 (2348, 0.1),
 (2412, 0.1),
 (2514, 0.1),
 (2831, 0.1),
 (2847, 0.1),
 (3235, 0.1),
 (3413, 0.1),
 (3525, 0.1),
 (3577, 0.1),
 (4054, 0.1),
 (4129, 0.1),
 (4201, 0.1),
 (4747, 0.1),
 (65, 0.09922778767136678),
 (4613, 0.09922778767136678),
 (329, 0.09863939238321438),
 (471, 0.09863939238321438),
 (1046, 0.09863939238321438),
 (1078, 0.09863939238321438),
 (1507, 0.09863939238321438),
 (1804, 0.09863939238321438),
 (2173, 0.09863939238321438),
 (2971, 0.09863939238321438),
 (3908, 0.09863939238321438),
 (4082, 0.09863939238321438),
 (1563, 0.09847319278346618),
 (2918, 0.09773555548504419),
 (71, 0.09733285267845754),
 (210, 0.09733285267845754),
 (211, 0.09733285267845754),
 (350, 0.09733285267845754),
 (436, 0.09733285267845754),
 (835, 0.09733285267845754),
 (1264, 0.09733285267845754),
 (1294, 0.09733285267845754),
 (2419, 0.09733285267845754),
 (2432, 0.09733285267845754),
 (2477, 0.09733285267845754),
 (151, 0.09701425001453319),
 (189, 0.09701425001453319),
 (205, 0.09701425001453319),
 (321, 0.09701425001453319),
 (653, 0.09701425001453319),
 (1043, 0.09701425001453319),
 (1595, 0.09701425001453319),
 (1609, 0.09701425001453319),
 (2690, 0.09701425001453319),
 (2759, 0.09701425001453319),
 (3709, 0.09701425001453319),
 (3777, 0.09701425001453319),
 (70, 0.09607689228305229),
 (522, 0.09607689228305229),
 (592, 0.09607689228305229),
 (807, 0.09607689228305229),
 (1007, 0.09607689228305229),
 (1557, 0.09607689228305229),
 (1725, 0.09607689228305229),
 (1796, 0.09607689228305229),
 (1843, 0.09607689228305229),
 (2005, 0.09607689228305229),
 (2986, 0.09607689228305229),
 (3005, 0.09607689228305229),
 (3204, 0.09607689228305229),
 (3700, 0.09607689228305229),
 (1851, 0.09561828874675149),
 (78, 0.09486832980505139),
 (168, 0.09486832980505139),
 (605, 0.09486832980505139),
 (898, 0.09486832980505139),
 (1054, 0.09486832980505139),
 (1121, 0.09486832980505139),
 (3662, 0.09486832980505139),
 (489, 0.09428090415820635),
 (699, 0.09428090415820635),
 (966, 0.09428090415820635),
 (1298, 0.09428090415820635),
 (1473, 0.09428090415820635),
 (1517, 0.09428090415820635),
 (1921, 0.09428090415820635),
 (2085, 0.09428090415820635),
 (2309, 0.09428090415820635),
 (2313, 0.09428090415820635),
 (2349, 0.09428090415820635),
 (2377, 0.09428090415820635),
 (2617, 0.09428090415820635),
 (3215, 0.09428090415820635),
 (3623, 0.09428090415820635),
 (3719, 0.09428090415820635),
 (4018, 0.09428090415820635),
 (113, 0.09370425713316365),
 (430, 0.09370425713316365),
 (788, 0.09370425713316365),
 (2767, 0.09370425713316365),
 (3928, 0.09370425713316365),
 (4173, 0.09370425713316365),
 (4262, 0.09370425713316365),
 (225, 0.09258200997725516),
 (340, 0.09258200997725516),
 (347, 0.09258200997725516),
 (583, 0.09258200997725516),
 (591, 0.09258200997725516),
 (1015, 0.09258200997725516),
 (1069, 0.09258200997725516),
 (2863, 0.09258200997725516),
 (4382, 0.09258200997725516),
 (2350, 0.09258200997725514),
 (461, 0.0917662935482247),
 (627, 0.0917662935482247),
 (796, 0.0917662935482247),
 (916, 0.0917662935482247),
 (1366, 0.0917662935482247),
 (1369, 0.0917662935482247),
 (1778, 0.0917662935482247),
 (2208, 0.0917662935482247),
 (2441, 0.0917662935482247),
 (2738, 0.0917662935482247),
 (3690, 0.0917662935482247),
 (3998, 0.0917662935482247),
 (4243, 0.0917662935482247),
 (191, 0.0914991421995628),
 (683, 0.0914991421995628),
 (1619, 0.0914991421995628),
 (1837, 0.0914991421995628),
 (2088, 0.0914991421995628),
 (2669, 0.0914991421995628),
 (730, 0.09116846116771037),
 (4678, 0.09116846116771037),
 (89, 0.09090909090909093),
 (1109, 0.09058216273156766),
 (419, 0.09045340337332909),
 (473, 0.09045340337332909),
 (813, 0.09045340337332909),
 (888, 0.09045340337332909),
 (1579, 0.09045340337332909),
 (4061, 0.09045340337332909),
 (531, 0.0894427190999916),
 (728, 0.0894427190999916),
 (831, 0.0894427190999916),
 (833, 0.0894427190999916),
 (1166, 0.0894427190999916),

In [129]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [130]:
recommend('John Carter')

Star Trek: Insurrection
Mission to Mars
Captain America: The First Avenger
Escape from Planet Earth
Ghosts of Mars

In [131]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [132]:
import pickle

In [133]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))